create table if not exists member_user (
    id              bigint generated by default as identity primary key,
    username        varchar(64) not null unique,
    password_hash   varchar(255) not null,
    phone           varchar(32),
    email           varchar(128),
    display_name    varchar(64),
    status          varchar(16) not null default 'ACTIVE',
    deleted         boolean not null default false,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp
);

create unique index if not exists uk_member_user_username_deleted
on member_user(username, deleted);

create unique index if not exists uk_member_user_phone_deleted
on member_user(phone, deleted);

create unique index if not exists uk_member_user_email_deleted
on member_user(email, deleted);

create index if not exists idx_member_user_status_deleted
on member_user(status, deleted);

create table if not exists member_verify_code (
    id              bigint generated by default as identity primary key,
    target_type     varchar(16) not null,
    target_value    varchar(128) not null,
    verify_code     varchar(32) not null,
    expires_at      timestamp not null,
    used            boolean not null default false,
    deleted         boolean not null default false,
    created_at      timestamp not null default current_timestamp
);

create index if not exists idx_member_verify_code_target
on member_verify_code(target_type, target_value, used, deleted);

create table if not exists member_login_session (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    token           varchar(128) not null,
    grant_type      varchar(16) not null,
    expires_at      timestamp not null,
    revoked         boolean not null default false,
    deleted         boolean not null default false,
    created_at      timestamp not null default current_timestamp
);

create unique index if not exists uk_member_login_session_token_deleted
on member_login_session(token, deleted);

create index if not exists idx_member_login_session_user_id_deleted
on member_login_session(user_id, deleted);
