-- ============================================================
-- Script type: baseline
-- Version: B20260423
-- Module: rag
-- Description: RAG schema in the main application database.
-- Notes:
--   1. This script does not create a new database.
--   2. All RAG tables use the t_ prefix.
--   3. user_id points to t_user.user_id by logical reference.
--   4. Embedding vectors are stored in PostgreSQL pgvector.
-- ============================================================

create extension if not exists vector;

create table if not exists t_ingestion_pipeline (
    id             bigint generated by default as identity,
    name           varchar(100) not null,
    description    text default null,
    created_by     bigint default null,
    updated_by     bigint default null,
    deleted        smallint not null default 0,
    created_at     timestamp not null default current_timestamp,
    updated_at     timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_ingestion_pipeline_name_deleted unique (name, deleted)
);
create index if not exists idx_t_ingestion_pipeline_created_by on t_ingestion_pipeline (created_by);

create table if not exists t_ingestion_pipeline_node (
    id             bigint generated by default as identity,
    pipeline_id    bigint not null,
    node_id        varchar(64) not null,
    node_type      varchar(30) not null,
    next_node_id   varchar(64) default null,
    settings_json  jsonb default null,
    condition_json jsonb default null,
    created_by     bigint default null,
    updated_by     bigint default null,
    deleted        smallint not null default 0,
    created_at     timestamp not null default current_timestamp,
    updated_at     timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_ingestion_pipeline_node unique (pipeline_id, node_id, deleted)
);
create index if not exists idx_t_ingestion_pipeline_node_pipeline on t_ingestion_pipeline_node (pipeline_id);

create table if not exists t_knowledge_base (
    id              bigint generated by default as identity,
    name            varchar(128) not null,
    description     varchar(512) default null,
    embedding_model varchar(128) not null,
    collection_name varchar(128) not null,
    visibility      varchar(16) not null default 'PRIVATE',
    status          varchar(16) not null default 'ACTIVE',
    owner_user_id   bigint default null,
    created_by      bigint default null,
    updated_by      bigint default null,
    deleted         smallint not null default 0,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_knowledge_base_collection_deleted unique (collection_name, deleted)
);
create index if not exists idx_t_knowledge_base_name_deleted on t_knowledge_base (name, deleted);
create index if not exists idx_t_knowledge_base_owner_deleted on t_knowledge_base (owner_user_id, deleted);

create table if not exists t_knowledge_document (
    id               bigint generated by default as identity,
    kb_id            bigint not null,
    doc_name         varchar(256) not null,
    enabled          smallint not null default 1,
    chunk_count      int not null default 0,
    file_url         varchar(1024) default null,
    file_type        varchar(32) default null,
    file_size        bigint default null,
    process_mode     varchar(32) not null default 'chunk',
    status           varchar(32) not null default 'pending',
    source_type      varchar(32) default null,
    source_location  varchar(1024) default null,
    content_hash     varchar(128) default null,
    schedule_enabled smallint not null default 0,
    schedule_cron    varchar(128) default null,
    chunk_strategy   varchar(32) default null,
    chunk_config     jsonb default null,
    pipeline_id      bigint default null,
    created_by       bigint default null,
    updated_by       bigint default null,
    deleted          smallint not null default 0,
    created_at       timestamp not null default current_timestamp,
    updated_at       timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_doc_kb_deleted on t_knowledge_document (kb_id, deleted);
create index if not exists idx_t_doc_status_deleted on t_knowledge_document (status, deleted);
create index if not exists idx_t_doc_created_by on t_knowledge_document (created_by);
create index if not exists idx_t_doc_content_hash on t_knowledge_document (content_hash);

create table if not exists t_knowledge_chunk (
    id           bigint generated by default as identity,
    kb_id        bigint not null,
    doc_id       bigint not null,
    chunk_index  int not null,
    content      text not null,
    content_hash varchar(128) default null,
    char_count   int default null,
    token_count  int default null,
    enabled      smallint not null default 1,
    metadata     jsonb default null,
    created_by   bigint default null,
    updated_by   bigint default null,
    deleted      smallint not null default 0,
    created_at   timestamp not null default current_timestamp,
    updated_at   timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_chunk_doc_index_deleted unique (doc_id, chunk_index, deleted)
);
create index if not exists idx_t_chunk_kb_deleted on t_knowledge_chunk (kb_id, deleted);
create index if not exists idx_t_chunk_doc_deleted on t_knowledge_chunk (doc_id, deleted);
create index if not exists idx_t_chunk_hash on t_knowledge_chunk (content_hash);

create table if not exists t_knowledge_vector (
    id              bigint generated by default as identity,
    kb_id           bigint not null,
    doc_id          bigint not null,
    chunk_id        bigint not null,
    collection_name varchar(128) not null,
    vector_id       varchar(128) not null,
    embedding_model varchar(128) not null,
    embedding_dim   int default null,
    metadata        jsonb default null,
    content         text not null,
    embedding       vector(1536) not null,
    created_by      bigint default null,
    deleted         smallint not null default 0,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_knowledge_vector_chunk_deleted unique (chunk_id, deleted),
    constraint uk_t_knowledge_vector_vector_deleted unique (collection_name, vector_id, deleted)
);
create index if not exists idx_t_knowledge_vector_kb_deleted on t_knowledge_vector (kb_id, deleted);
create index if not exists idx_t_knowledge_vector_doc_deleted on t_knowledge_vector (doc_id, deleted);
create index if not exists idx_t_knowledge_vector_collection_deleted on t_knowledge_vector (collection_name, deleted);
create index if not exists idx_t_knowledge_vector_metadata on t_knowledge_vector using gin (metadata);
create index if not exists idx_t_knowledge_vector_embedding_hnsw on t_knowledge_vector using hnsw (embedding vector_cosine_ops);

create table if not exists t_knowledge_document_chunk_log (
    id                bigint generated by default as identity,
    doc_id            bigint not null,
    status            varchar(20) not null,
    process_mode      varchar(20) default null,
    chunk_strategy    varchar(50) default null,
    pipeline_id       bigint default null,
    extract_duration  bigint default null,
    chunk_duration    bigint default null,
    embed_duration    bigint default null,
    persist_duration  bigint default null,
    total_duration    bigint default null,
    chunk_count       int default null,
    error_message     text default null,
    started_at        timestamp default null,
    ended_at          timestamp default null,
    created_at        timestamp not null default current_timestamp,
    updated_at        timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_doc_chunk_log_doc on t_knowledge_document_chunk_log (doc_id);
create index if not exists idx_t_doc_chunk_log_status on t_knowledge_document_chunk_log (status);
create index if not exists idx_t_doc_chunk_log_started on t_knowledge_document_chunk_log (started_at);

create table if not exists t_knowledge_document_schedule (
    id                bigint generated by default as identity,
    doc_id            bigint not null,
    kb_id             bigint not null,
    cron_expr         varchar(128) default null,
    enabled           smallint not null default 0,
    next_run_time     timestamp default null,
    last_run_time     timestamp default null,
    last_success_time timestamp default null,
    last_status       varchar(32) default null,
    last_error        varchar(512) default null,
    last_etag         varchar(256) default null,
    last_modified     varchar(256) default null,
    last_content_hash varchar(128) default null,
    lock_owner        varchar(128) default null,
    lock_until        timestamp default null,
    created_at        timestamp not null default current_timestamp,
    updated_at        timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_doc_schedule_doc unique (doc_id)
);
create index if not exists idx_t_doc_schedule_kb on t_knowledge_document_schedule (kb_id);
create index if not exists idx_t_doc_schedule_next_run on t_knowledge_document_schedule (next_run_time);
create index if not exists idx_t_doc_schedule_lock_until on t_knowledge_document_schedule (lock_until);

create table if not exists t_knowledge_document_schedule_exec (
    id            bigint generated by default as identity,
    schedule_id   bigint not null,
    doc_id        bigint not null,
    kb_id         bigint not null,
    status        varchar(32) not null,
    message       varchar(512) default null,
    started_at    timestamp default null,
    ended_at      timestamp default null,
    file_name     varchar(512) default null,
    file_size     bigint default null,
    content_hash  varchar(128) default null,
    etag          varchar(256) default null,
    last_modified varchar(256) default null,
    created_at    timestamp not null default current_timestamp,
    updated_at    timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_doc_schedule_exec_schedule_time on t_knowledge_document_schedule_exec (schedule_id, started_at);
create index if not exists idx_t_doc_schedule_exec_doc on t_knowledge_document_schedule_exec (doc_id);
create index if not exists idx_t_doc_schedule_exec_kb on t_knowledge_document_schedule_exec (kb_id);

create table if not exists t_ingestion_task (
    id               bigint generated by default as identity,
    pipeline_id      bigint default null,
    kb_id            bigint default null,
    doc_id           bigint default null,
    source_type      varchar(20) not null,
    source_location  text default null,
    source_file_name varchar(255) default null,
    status           varchar(20) not null,
    chunk_count      int not null default 0,
    error_message    text default null,
    logs_json        jsonb default null,
    metadata_json    jsonb default null,
    started_at       timestamp default null,
    completed_at     timestamp default null,
    created_by       bigint default null,
    updated_by       bigint default null,
    deleted          smallint not null default 0,
    created_at       timestamp not null default current_timestamp,
    updated_at       timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_ingestion_task_pipeline on t_ingestion_task (pipeline_id);
create index if not exists idx_t_ingestion_task_kb_doc on t_ingestion_task (kb_id, doc_id);
create index if not exists idx_t_ingestion_task_status on t_ingestion_task (status);
create index if not exists idx_t_ingestion_task_created_by on t_ingestion_task (created_by);

create table if not exists t_ingestion_task_node (
    id            bigint generated by default as identity,
    task_id       bigint not null,
    pipeline_id   bigint default null,
    node_id       varchar(64) not null,
    node_type     varchar(30) not null,
    node_order    int not null default 0,
    status        varchar(20) not null,
    duration_ms   bigint not null default 0,
    message       text default null,
    error_message text default null,
    output_json   text default null,
    deleted       smallint not null default 0,
    created_at    timestamp not null default current_timestamp,
    updated_at    timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_ingestion_task_node_task on t_ingestion_task_node (task_id);
create index if not exists idx_t_ingestion_task_node_pipeline on t_ingestion_task_node (pipeline_id);
create index if not exists idx_t_ingestion_task_node_status on t_ingestion_task_node (status);

create table if not exists t_conversation (
    id              bigint generated by default as identity,
    conversation_id varchar(64) not null,
    user_id         bigint not null,
    title           varchar(128) not null,
    last_time       timestamp default null,
    deleted         smallint not null default 0,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_conversation_user unique (conversation_id, user_id)
);
create index if not exists idx_t_conversation_user_time on t_conversation (user_id, last_time);
create index if not exists idx_t_conversation_deleted on t_conversation (deleted);

create table if not exists t_conversation_summary (
    id              bigint generated by default as identity,
    conversation_id varchar(64) not null,
    user_id         bigint not null,
    last_message_id bigint not null,
    content         text not null,
    deleted         smallint not null default 0,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_conversation_summary_conv_user on t_conversation_summary (conversation_id, user_id);

create table if not exists t_message (
    id                bigint generated by default as identity,
    conversation_id   varchar(64) not null,
    user_id           bigint not null,
    role              varchar(32) not null,
    content           text not null,
    thinking_content  text default null,
    thinking_duration int default null,
    metadata          jsonb default null,
    deleted           smallint not null default 0,
    created_at        timestamp not null default current_timestamp,
    updated_at        timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_message_conv_user_time on t_message (conversation_id, user_id, created_at);
create index if not exists idx_t_message_user_time on t_message (user_id, created_at);

create table if not exists t_message_feedback (
    id              bigint generated by default as identity,
    message_id      bigint not null,
    conversation_id varchar(64) not null,
    user_id         bigint not null,
    vote            smallint not null,
    reason          varchar(255) default null,
    comment         varchar(1024) default null,
    deleted         smallint not null default 0,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_message_feedback_msg_user unique (message_id, user_id)
);
create index if not exists idx_t_message_feedback_conversation on t_message_feedback (conversation_id);
create index if not exists idx_t_message_feedback_user on t_message_feedback (user_id);

create table if not exists t_sample_question (
    id          bigint generated by default as identity,
    kb_id       bigint default null,
    title       varchar(64) default null,
    description varchar(255) default null,
    question    varchar(1024) not null,
    sort_order  int not null default 0,
    enabled     smallint not null default 1,
    deleted     smallint not null default 0,
    created_at  timestamp not null default current_timestamp,
    updated_at  timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_sample_question_kb_deleted on t_sample_question (kb_id, deleted);
create index if not exists idx_t_sample_question_enabled on t_sample_question (enabled, deleted);

create table if not exists t_intent_node (
    id                    bigint generated by default as identity,
    kb_id                 bigint default null,
    intent_code           varchar(64) not null,
    name                  varchar(64) not null,
    level                 smallint not null,
    parent_code           varchar(64) default null,
    description           varchar(512) default null,
    examples              text default null,
    collection_name       varchar(128) default null,
    top_k                 int default null,
    mcp_tool_id           varchar(128) default null,
    kind                  smallint not null default 0,
    prompt_snippet        text default null,
    prompt_template       text default null,
    param_prompt_template text default null,
    sort_order            int not null default 0,
    enabled               smallint not null default 1,
    created_by            bigint default null,
    updated_by            bigint default null,
    deleted               smallint not null default 0,
    created_at            timestamp not null default current_timestamp,
    updated_at            timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_intent_code_deleted unique (intent_code, deleted)
);
create index if not exists idx_t_intent_kb_deleted on t_intent_node (kb_id, deleted);
create index if not exists idx_t_intent_parent on t_intent_node (parent_code);
create index if not exists idx_t_intent_enabled on t_intent_node (enabled, deleted);

create table if not exists t_query_term_mapping (
    id          bigint generated by default as identity,
    domain      varchar(64) default null,
    source_term varchar(128) not null,
    target_term varchar(128) not null,
    match_type  smallint not null default 1,
    priority    int not null default 100,
    enabled     smallint not null default 1,
    remark      varchar(255) default null,
    created_by  bigint default null,
    updated_by  bigint default null,
    deleted     smallint not null default 0,
    created_at  timestamp not null default current_timestamp,
    updated_at  timestamp not null default current_timestamp,
    primary key (id)
);
create index if not exists idx_t_term_domain on t_query_term_mapping (domain);
create index if not exists idx_t_term_source on t_query_term_mapping (source_term);
create index if not exists idx_t_term_enabled on t_query_term_mapping (enabled, deleted);

create table if not exists t_rag_trace_run (
    id              bigint generated by default as identity,
    trace_id        varchar(64) not null,
    trace_name      varchar(128) default null,
    entry_method    varchar(256) default null,
    conversation_id varchar(64) default null,
    task_id         varchar(64) default null,
    user_id         bigint default null,
    status          varchar(16) not null default 'RUNNING',
    error_message   varchar(1000) default null,
    started_at      timestamp(3) default null,
    ended_at        timestamp(3) default null,
    duration_ms     bigint default null,
    extra_data      jsonb default null,
    deleted         smallint not null default 0,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_rag_trace_run_trace unique (trace_id)
);
create index if not exists idx_t_rag_trace_run_task on t_rag_trace_run (task_id);
create index if not exists idx_t_rag_trace_run_user on t_rag_trace_run (user_id);
create index if not exists idx_t_rag_trace_run_status on t_rag_trace_run (status);

create table if not exists t_rag_trace_node (
    id             bigint generated by default as identity,
    trace_id       varchar(64) not null,
    node_id        varchar(64) not null,
    parent_node_id varchar(64) default null,
    depth          int not null default 0,
    node_type      varchar(64) default null,
    node_name      varchar(128) default null,
    class_name     varchar(256) default null,
    method_name    varchar(128) default null,
    status         varchar(16) not null default 'RUNNING',
    error_message  varchar(1000) default null,
    started_at     timestamp(3) default null,
    ended_at       timestamp(3) default null,
    duration_ms    bigint default null,
    extra_data     jsonb default null,
    deleted        smallint not null default 0,
    created_at     timestamp not null default current_timestamp,
    updated_at     timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_rag_trace_node_run_node unique (trace_id, node_id)
);
create index if not exists idx_t_rag_trace_node_parent on t_rag_trace_node (trace_id, parent_node_id);
create index if not exists idx_t_rag_trace_node_status on t_rag_trace_node (status);


