package com.personalblog.ragbackend.knowledge.service.vector;

import com.personalblog.ragbackend.knowledge.config.KnowledgeProperties;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@ConditionalOnBean(JdbcTemplate.class)
@ConditionalOnExpression("'${rag.vector.type:pg}'.toLowerCase() == 'pgvector' or '${rag.vector.type:pg}'.toLowerCase() == 'pg'")
public class PgVectorStoreAdmin implements VectorStoreAdmin {
    private final JdbcTemplate jdbcTemplate;
    private final KnowledgeProperties knowledgeProperties;

    public PgVectorStoreAdmin(JdbcTemplate jdbcTemplate, KnowledgeProperties knowledgeProperties) {
        this.jdbcTemplate = jdbcTemplate;
        this.knowledgeProperties = knowledgeProperties;
    }

    @Override
    public void ensureVectorSpace(KnowledgeVectorSpace vectorSpace) {
        String schema = identifier(knowledgeProperties.getVector().getPg().getSchema());
        String table = identifier(knowledgeProperties.getVector().getPg().getTableName());
        String qualifiedTable = schema + "." + table;
        jdbcTemplate.execute("create schema if not exists " + schema);
        jdbcTemplate.execute("create extension if not exists vector");
        jdbcTemplate.execute("""
                create table if not exists %s (
                    id bigint generated by default as identity primary key,
                    kb_id bigint,
                    doc_id bigint,
                    chunk_id bigint,
                    collection_name varchar(128) not null,
                    vector_id varchar(128) not null,
                    embedding_model varchar(128) not null,
                    embedding_dim integer,
                    content text not null,
                    metadata jsonb,
                    embedding vector(%d) not null,
                    created_by bigint,
                    deleted smallint not null default 0,
                    create_time timestamp not null default current_timestamp,
                    update_time timestamp not null default current_timestamp
                )
                """.formatted(qualifiedTable, vectorSpace.dimension()));
        jdbcTemplate.execute("""
                create unique index if not exists uk_t_knowledge_vector_chunk_deleted
                on %s (chunk_id, deleted)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create unique index if not exists uk_t_knowledge_vector_vector_deleted
                on %s (collection_name, vector_id, deleted)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create index if not exists idx_t_knowledge_vector_collection_deleted
                on %s (collection_name, deleted)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create index if not exists idx_t_knowledge_vector_metadata
                on %s using gin (metadata)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create index if not exists idx_t_knowledge_vector_embedding_hnsw
                on %s using hnsw (embedding vector_cosine_ops)
                """.formatted(qualifiedTable));
    }

    @Override
    public boolean vectorSpaceExists(KnowledgeVectorSpaceId spaceId, String collectionName) {
        String schema = knowledgeProperties.getVector().getPg().getSchema();
        String tableName = knowledgeProperties.getVector().getPg().getTableName();
        Integer count = jdbcTemplate.queryForObject("""
                select count(*)
                from information_schema.tables
                where table_schema = ? and table_name = ?
                """, Integer.class, schema, tableName);
        return count != null && count > 0;
    }

    private String identifier(String value) {
        if (value == null || !value.matches("[A-Za-z_][A-Za-z0-9_]*")) {
            throw new IllegalArgumentException("Invalid PostgreSQL identifier: " + value);
        }
        return value;
    }
}
