create table if not exists sys_user (
    user_id         bigint generated by default as identity primary key,
    username        varchar(64) not null,
    password_hash   varchar(255) not null,
    phone           varchar(32),
    email           varchar(128),
    display_name    varchar(64),
    user_type       varchar(16) not null default 'USER',
    status          varchar(16) not null default 'ACTIVE',
    deleted         tinyint not null default 0,
    created_at      timestamp not null default current_timestamp,
    updated_at      timestamp not null default current_timestamp
);

create table if not exists sys_verify_code_record (
    record_id       bigint generated by default as identity primary key,
    biz_type        varchar(64) not null,
    biz_id          varchar(64),
    subject_type    varchar(32),
    subject_id      bigint,
    target_type     varchar(16) not null,
    target_value    varchar(128) not null,
    channel         varchar(16) not null default 'SMS',
    template_id     varchar(100),
    provider        varchar(64),
    request_id      varchar(128),
    code_value      varchar(64) not null,
    expires_at      timestamp not null,
    used            boolean not null default false,
    used_at         timestamp,
    deleted         tinyint not null default 0,
    created_at      timestamp not null default current_timestamp,
    remark          varchar(500)
);

create table if not exists sys_auth_session (
    session_id      bigint generated by default as identity primary key,
    subject_id      bigint not null,
    subject_type    varchar(32) not null,
    login_type      varchar(32) not null,
    token_digest    varchar(64) not null,
    expires_at      timestamp not null,
    revoked         boolean not null default false,
    deleted         tinyint not null default 0,
    created_at      timestamp not null default current_timestamp,
    last_active_at  timestamp not null default current_timestamp,
    device_type     varchar(32),
    client_ip       varchar(64)
);

create unique index if not exists uk_sys_user_username_deleted on sys_user (username, deleted);
create unique index if not exists uk_sys_user_phone_deleted on sys_user (phone, deleted);
create unique index if not exists uk_sys_user_email_deleted on sys_user (email, deleted);
create index if not exists idx_sys_user_status_deleted on sys_user (status, deleted);
create index if not exists idx_sys_user_user_type_deleted on sys_user (user_type, deleted);

create index if not exists idx_sys_verify_code_record_lookup
    on sys_verify_code_record (biz_type, target_type, target_value, code_value, used, deleted, expires_at);
create index if not exists idx_sys_verify_code_record_subject
    on sys_verify_code_record (subject_type, subject_id, deleted);
create index if not exists idx_sys_verify_code_record_request_id on sys_verify_code_record (request_id);

create unique index if not exists uk_sys_auth_session_token_digest_deleted
    on sys_auth_session (token_digest, deleted);
create index if not exists idx_sys_auth_session_subject_deleted
    on sys_auth_session (subject_id, subject_type, revoked, deleted);
create index if not exists idx_sys_auth_session_expires_at on sys_auth_session (expires_at);
